### ISSUE TITLE
10 - Tuple to Union

### ISSUE THREAD

**Issue by mefengl** [type-challenges/type-challenges#18545]
```ts
// use [number] for array, keyof for object
type TupleToUnion<T extends unknown[]> = T[number]
```

**Comment by daniel-hyun-chae** [comment]
I was expecting that "T extends unknown[]" does not express tuple correctly because an array of certain type e.g. string[] can be consisted only one type (in this case string). Whereas, tuple can contain multiple types. I was rather expecting something like "T extends [...any]". But at the same time, I'm surprised that type TupleToUnion<T extends unknown[]> = T[number] can accept "[123, '456', true]" as T.. Can anyone explain why this is possible?
