### ISSUE TITLE
10969 - Integer

### ISSUE THREAD

**Issue by santosmarco-caribou** [type-challenges/type-challenges#18773]
```ts
type Integer<T extends number> = `${T}` extends `${bigint}` ? T : never
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgUABBCMAMCcA2eEC0ECSA7ALgUwHM8AnSNVCysgIwE8IAJAVwEMAhASywIgAoABABbUAxsRYAzHAEoIAYgC2eACYcmC+fgUAHADYt8qXR3zjdZMnKsQAikzwBnHBwD2WC1AAKuvCwd4IERcdH3wIHFptAIADbHwiYgAeABUAPmiAGnDImOToiC5BEhMHCAliYIhorHVqEkyCiSq8gtKWLALcQhIIYjwcJmIOkyyXHCLiAHcOf17+wY7qvAA3eoA6DwhUiAA1DjxJiDcIAHETZmoALghBHBxtB0vgYBwHEUE1gCsHNZdiAmAcCQ8DAIGAYAhoAgAH1YXD4XCIABNFyDCAAYRcygCDBIAQRBNhEDBEIiUUwXQSKQgeAAHvgsMpSjUFHViNsALxVAAkAG9kgBffJ0hlMnm86gcAhcHBCiAAfggyQg1ywKxIELAUMJBKVjhwGL8jhhOvhxPBHB0fwNZICvIgAFEAI6sXRZB20qIiA0CsoVDQAcn4ttQ7xYuh83EcwCYzl0DgDYEt2mtEHtHq9OAAYuH-FkAHJjZ2uiC+8qVIMhsMRvBRhwxuMJiGhCC0iBc6BgFv0DsQPyBNxOUk5QJGhzQdsQADaZAzeG9iWL4cScW6SWgqSyG83s8985wi5dy9XVOgaw3WTVq3ZO6gc4XS90K8pJESZ9gm5gqVvjr3D6PT4nq+touE0tKfleJDfhku6ZoerrPvEwE5KBEC0J+24wQAupqWogCappElmgzjD0ADK+APARhHmnhZDbGRggsH0aGosQEAOC4uixq4WCPDcdwPE8LxvB83y-P8gIIMgwDtA4kwalA2x7AcHFcTxg7XLc9yPM8rzvF8Px-ACQIyZx3HOIO9EQAAsn8ATokxNZ1lpgm6SJBnicZoLgmAQA)

**Comment by zhl1232** [comment]
How is it happen?

**Comment by Sjoertjuh** [comment]
@zhl1232 The `bigint` type is forced to be absolute, so it can't be extended by a number with decimal digits

**Comment by EasyRo** [comment]
i don't understand how does it work

**Comment by kaascevich** [comment]
@CyrusHelios From what I understand, `` `${T}` extends `${bigint}` `` effectively checks if the string representation of `T` would also work as a string representation of a `bigint`. For example:
- `42` would pass this check, because it's possible to get `"42"` by calling `toString` on a `bigint`.
- `3.141` would _not_ pass this check, because `bigint`s have to be integers; it's not possible to get `"3.141"` by calling `toString` on a `bigint`.

The string casts are necessary simply because `number` isn't assignable to `bigint` (or vice versa) in TypeScript, so `T extends bigint` would always be false in this case.
