### ISSUE TITLE
11 - Tuple to Object

### ISSUE THREAD

**Issue by MLopezJ** [type-challenges/type-challenges#24725]
## Solution
```ts
type allowedListType = string  | number 

/*

// my inital solution
type TupleToObject<T extends readonly allowedListType[]> = {
  [key in keyof T] : key  
}

Questions: 

1- Why 'keyof' doesnt work there?
2- What does 'number' means in the solution below? What about strings??
*/

// after check other solutions
type TupleToObject<T extends readonly allowedListType[]> = {
  [key in T[number]] : key  
}
```

## Use
```ts
const list = [1,2,3, 4] as const
type result = TupleToObject<typeof list>
const useOfTypeResult: result = {
  1:1,
  2:2,
  3:3,
  4: 4
}

// Error expected below: 

const wrongUseOfTypeResult : result = [1,2,3,4]
const otherWrongUse : result = "hola"
const lastWrongCase : result = {
  "1": "1",
  2: "2",
  "3": 3,
  4: 4
}
```

## Description
Given an array, transform it into an object type and the key/value must be in the provided array.

## [Link](https://github.com/type-challenges/type-challenges/blob/main/questions/00011-easy-tuple-to-object/README.md)

**Comment by jckdn** [comment]
To answer your questions:

1. `keyof` on an array type seems to just get `number`, because that's the type that TS allows when indexing into arrays. But we want the type of the array/tuple's elements. 
2. See https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html
If `T` is an array or tuple or array-like object then `T[number]` gets the type of its elements that are accessible when using type `number` as the key.
`T[string]` seems only allowed when `T` has been defined as an object type that also has a string index signature like `type SomeObj = { [index: string]: boolean }`

Actually, it seems when using indexed access types you can pass in any type that can be used as a key to access properties of `T` (I guess it must be assignable to `keyof T`).

```TS
type Obj = { 
  [index: string]: boolean
  foo: true;
  '1': false;
}

type AccessedByString = Obj[string] // type: boolean
type AccessedByNumber = Obj[number] // type: boolean (I was surprised that this is allowed!)
type AccessedByFoo = Obj['foo'] // type: true
type AccessedBy1 = Obj[1] // type: false
type AccessedByStringy1 = Obj['1'] // type: false
type AccessedByVarious = Obj[number | string | 'foo' | 42] // type: boolean
```
