### ISSUE TITLE
462 - Currying 2

### ISSUE THREAD

**Issue by suica** [type-challenges/type-challenges#761]
```ts
declare function DynamicParamsCurrying<T extends any, P extends any[]>(fn: (...args: [...P]) => T): CurringHelper<[], P, T>
type CurringHelper<Old extends any[], Total extends any[], Ret> = Old['length'] extends Total['length'] ? Ret : <New extends any[]>(...args: New) => CurringHelper<[...Old, ...New], Total, Ret>
```

**Comment by Beraliv** [comment]
I have a problem with this solution:

```ts
const curried1 = DynamicParamsCurrying((a: string, b: number, c: boolean) => true)

const a = curried1('123', 123, curried1)
```

The third parameter is infered as `any` when I pass 3rd parameter:

```ts
(args_0: string, args_1: number, args_2: any): boolean
```

[Playground](https://www.typescriptlang.org/play?#code/PQKgsAUABFAsBsAmKBaKBhArgJ2wTwEsA7AcykUhhWppUqgCM8oBpAgWygAoABAC0wMAbpgCmASigBiUQA8ALtlHtRUevSmaoARTEBneQQD2RddCgBtLLkKkAulz7z5ABz0AuYMFFEAdAHcCAGsCF1EAEwIAQ18jbBJgQJDga3xiEkkCPSh5PlV5UQBjPiICAEcxKCMAMyhCkyFRbENSKCioaswiQsMTHL4o+RyooNFs9kwAG0MXSdUo+MwVInls4nkjNqg9UQqfQtUajq6e4yJs3MGoUSji4dGtvXS5tsXl+V8zGAAhTCHiKo4KDhKIESbMSYEaqiAA0dRwaVa4TwRCi7AIhVeJCWPlWUCybUmek29XY7BM4KgmB24Th1Ti11kaNmsP6qgABgAxE69PwMYjhLi5LJwiy+cUuBZovR2cTsqAAQQACgBJT7mejsrWrej1c5DTrdKAAXm4UXcUCISwYTThDAtVvYNuwcMKDutTUkxoAfFAAN70GBKeQ4IhbADUjCgkcK9AAvl86iYDIwBdyjabDYUuFbJpM4QBGOGIcSJvUppR6KZDU38ojhdPZgDMki8UEr1Yt8E1WsTABUBHo7VEaVUw+zUrYyAX2XD-Kp-EYpuFLaIIjlNgNGmzgSi0RisTiVlBGtgniZ3ImteydeZy0MouEV6auObLR6XYx3U7bXVv86vV9dpIwYaM6l1ZMhlyJRVFNR9BSLKBEILSQy0g+FcAICIFSfE0oAAET3dFCiVKV2D0Sd0lfJ9SzvdCnlkPDCgRLDwhwhDizhFsIP1bZREaMNTWYzDsKfLhEJLLhYFomB72uAgSCcJiWNEwVJJbKSZKga9ExVMNhWyYoojzHwSFZdlCNRYjSOwaVKNIeV2CiZh5BGeZjm6XkoECXIoAALyaTYNigCZplCF4Fmxd4hygPAl1XddgvqXAinkSl5DwMJ8Q+KAB1UYNQ3XLMvKc5hbgOFwHyGOYRyGEx5jeXFfCgAB1PIw2MyYd0io88RHbZBiyapWLhAghj0Pgl0mFdCFEaadwK7B9Myw5alyQ5sAU4hjI804+mSpQenBdUYHoX0ADUsP8McoAAcTGgAJQQLScVwPC8VZil8AArPRYniYAEAoCAQGASBwYgUAoAAfVhuH4bhqAAE0l2wDAjHCVQHqaVQEbx2GoFBiHMcKSYFlUYqzgIoiMRsuyESnAAePtGQKetsiiIg8DhJVWZ8cIOa5iw7G9LhqiIC0uHFXxIo8SxpaVWUTV9PtxAtVJ0mxyYwmwRnhZ5uE+29SAMqyjXSC1nXGYAeXmuQ2YFtohbsQ2jFcrr7f5wW8H1qAACVRHkX1TVt8ILAAcjmUhcnDuw+fZ3K3eMiOo5IGO44Afn9wOoAtRmADlRGuz2E85n2Ral8VZYtMVxUL-wlZ9DAWItuardr3xQ7haX65dxP3bhAOg4hyAofxvHcrGIZ0BHMYYfH+HCbBiAOBcOIhj9KAAFEKmMuEt9kMIeigOMOmwIxOHDnhTdEFAjJM0gxmAP4wT0cOIbk4TNoiAs8Ms-cSJkQogzKir4LQGE2qQO0-5fxukYEYIwNUiCARyNgMQtFP4qXCMgU0-9rJAPsiQLgYDtiKHSNA98P5PxwIYAgpBcJwgWloYgm4RA4SiCYXQ1hdJwFkKgVAEgnCWGcxQYodBEM2xQnbMoIw24v6sV-tUc+nBJS2RUAUNGnMVwGAWFBTK6RR7AFivFQIeY+IcnkT-V88Q9DQwAAy8MgSQOEstoYFhgZ+VxiALRlzVvA4RRB2SQDku0ISWCCxcHDgWRATZw6Fhia6cJtFgnhK4OISJ0TYnxO4hAYJ6FLHhALEPUMv8wkiUKRkmJ4d0mZPSWIiQeTeIFKKYHUMOCMLfwqVEqp2T0nVGMjsDB+TwnFKWk2ZS5SIndKyUhBJqDxG5IgJg8piBRlEFKR01iiBKmxJqTEupaCJBiwGUc+p6TpnVOOUSBpSzhkrLWe0gp2yLm9KFIcukJyDliDhBcvpnzGkpieWs8ZZTOnPMyXE2ZGkzlXMGW875UAXkdH+bcppWDVmtKWrACZYKdmQsyXCGF-TrmEveYiiFfzrlDLRfczFRAACsOKtl4uyaS9BsLTmHPORSjl1LAXorWfAJlERwU9KhWy1kxK4X1J+RCj5VKAVDCBXSgA7MK7BLLxXzMlSciV3KxVSpucssFayAAc6rRUzIJdq+VOw9V4spYMxVmyRVrIAJwWs1damVyKSU2vJVUx1Rq7kmrpQWOxnqkXerJYaiVsqDUopNitOos9simgsPQA+R95CMx3pgYyjMcgrSOM0tZiFmFIO9N6GEmbD6pVzbvSYhab4lpGXSxAdouGcyrTW8wWb615oLUWsIrbJnAs7QEntEMYD9p6A2-NTbh2iFHaGkMS1y1dqIFOvtda52DsXS22oyq11EA7f4yt1ba3ZvnUOw9LrsHjvPaw7dM7d05v3c24tR6BV0tgBOi9vbX3Xo-UuldWy1n0v-c+y9O7gONs-SO79tKT3wCg92mDQGB3wdA0h1doYVVoa3Rh7eb6b0Hq-fejFJ7TWEZfSRuDC6EPLtw+BulbraPEdne+7Dd7j0lLsRx3tdgR6LLHgvRG3Jmh5DRgAZQKG4ee4noZL1HuAcwvoZMDCUMYoExJJgv2TC9ZwbhPDAE+nwH6f04gJCBsATmeh5zYDOlAS6RdtiIIM+cIzb1TPmcs-9GzSBgB6c83oZzABZOIqh0ADAfmZOWr0TMfT0F9X6AXIBE0WUAA)

I think `<New extends any[]>` is the reason, because it's not tied / connected with the original number of arguments

```ts
type CurringHelper<Old extends any[], Total extends any[], Ret> = Old['length'] extends Total['length'] ? Ret : <New extends Total>(...args: New) => CurringHelper<[...Old, ...New], Total, Ret>
```

This way it's working great but of course is limited only to be called with all parameters

So final solution will be to subtract all the values from `Total` having `Old`
